export default [
  {
    id: 1,
    icon: "https://img.icons8.com/ios-filled/256/women-shoes.png",
    name: "women shoes",
  },
  { id: 2,
    icon: "https://img.icons8.com/ios-filled/256/pair-of-sneakers.png",
    name: "sneakers",
  },
  { id: 3,
    icon: "https://img.icons8.com/doodle/256/children-shoes.png",
    name: "children shoes",
  },
  { id: 4,
    icon: "https://img.icons8.com/ios-filled/256/slippers.png",
    name: "slippers",
  },
  { id: 5,
    icon: "https://img.icons8.com/glyph-neue/256/school-backpack.png",
    name: "backpack",
  },
  { id: 6,
    icon: "https://img.icons8.com/fluency-systems-filled/256/puffer-jacket.png",
    name: "puffer jacket",
  },
  { id: 7,
    icon: "https://img.icons8.com/ios-glyphs/256/t-shirt.png",
    name: "T-shirt",
  },
];
